name 'bmcclure-sysstat'
version '2.0.11'

author 'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.benmcclure.com'
source 'https://github.com/bmcclure/puppet-sysstat'
summary 'Puppet module for sysstat'
description 'This module installs and manages sysstat. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
